### PR TITLE
Rit figma point list

### LINKED ISSUE #88: Make new, more descriptive point list from Figma
Adding a points list to the bottom of the page and matching the style to the figma design.

Point list preview:
image

The UI interaction to get to this point list is being finalized, but for now, just focus on getting the elements to look like they do in the mockup.

### PR DESCRIPTION
**Pull request by ritzz26**
image

Need to correct Mobile View, add logos and finish styling. 

#closes #88

### CODE REVIEW

**Comment by awest25** [comment]
Looks good so far, some things to note for styling:
- Add dividing lines and space them out a bit more
- Add the gradient background seen in the Figma
- make sure it displays properly on mobile

**Comment by ritzz26** [comment]
image


MOBILE:

image

**Review by awest25 — CHANGES_REQUESTED** [review]
Some things I'm noticing that can be improved:
- Heading rows should be smaller and lighter in color
- All values should be right aligned to their headings
- There should be play buttons (with no headings) on the right of each row
- DOM Manipulation: Every other page that we have uses JSX to render our elements. There should be no reason to use `document.createElement`. For consistency, readability, and maintainability, this should all be done as JSX.
- Same with styling. `th.style.fontSize` should not be used for the sake of consistency with the rest of the website.
- The images are not rendering for me right now, I believe it's because we swtiched around where logo URLs are stored (with the team now).
- Please please use more descriptive variable names. `opp` gives very little information. It should be `opponent_logo_url`.
- Remove debugging `console.log`s such as line 40 in page.js.

Once you make the fixes, please as ChatGPT if there is anything that can be improved in style, clarity, or approach, as specified in the pull request guidelines.

**Comment by ritzz26** [comment]
image

MOBILE:
image

**Comment by ritzz26** [comment]
image

**Review by awest25 — COMMENTED** [review]
It looks better but the styling of the point list is the main concern now as well as the functionality of the play button. Hovering over the play button should have a little hand cursor and clicking it should:
1. Reset the view to the top of the page so the video can be seen and 
2. Jump to that part of the video

There's also some styling issues, please see below, noticing the logo sizes, the spacing in each row, and the unessesary right alignment:
image

Please mimic what our design team produced:
image

**Comment by awest25** [comment]
Needs a few changes before merge, see #131

**Review by awest25 — APPROVED** [review]
looks fine

**Pull request merged**
