### PR TITLE
Separate pages into different URLs

### PR DESCRIPTION
**Pull request by krish1925**
Passing Document ID in the URL, dropdown issue still persists where selection doesn't get removed when you switch from one match to another, however everything else works fine, will add more params such as active filters in the next issue

### CODE REVIEW

**Review by Fredenck — CHANGES_REQUESTED** [review]
First of all, what's the extra empty <> </> tag for in the return statement? 

Second, why did you add another searchbar when we have one? Now there's a bug where one search bar can be a different match than the other.
image

Third, there's a highlighting bug that doesn't go away after your first selection
image

I'm going to mention this in the meeting, but please don't commit extraneous code and make sure everything is clean before you PR

**Comment by krish1925** [comment]
> First of all, what's the extra empty <> </> tag for in the return statement?
> 
> Second, why did you add another searchbar when we have one? Now there's a bug where one search bar can be a different match than the other. image
> 
> Third, there's a highlighting bug that doesn't go away after your first selection image
> 
> Fourth, you completely took out the filter display, why?
> 
> Plus, you took out an important function, removeFilter(). Now the site crashes when you try to remove a filter...
> 
> image image
> I'm going to mention this in the meeting, but please don't commit extraneous code and make sure everything is clean before you PR

I am already aware of these bugs, and this wasn't meant to be pushed until I fixed these changes. I told Alex about these bugs that existed (the ones that are listed above) but he wanted to take a look at how I was handling the dynamic pages so asked me to push the code (Given that he wasn't going to merge them until I confirmed that I fixed the bugs). I was going to fix these bugs before I gave the confirmation.

**Comment by Fredenck** [comment]
Ok, no worries. Please keep us updated with any changes or circumstances (like being busy or getting sick) in the future. In our meeting yesterday, both Jerry and I didn't know about your situation/this PR hence his message asking for an update in the chat and this review.

Rest up!

**Comment by Fredenck** [comment]
closed with app router migration: similar logic, but using app router instead of pages router (https://nextjs.org/docs/pages/building-your-application/upgrading/app-router-migration)

**Pull request closed without merging**
