### PR TITLE
Rit-Scoreboard beneath embedded video

### LINKED ISSUE #42: Add score underneath
- Right underneath the Youtube embed, add a graphic to indicate what the set/game score is and a dot next to who is serving.
- This should update when you jump to different parts of the video.
- This is made possible because we have the timestamps of each point and timestamp of the YT video

I would recommend looking into having a (Python) script to pre-process the csv data into a new column. That way, you can just read values from the csv  in the frontend.

image

### PR DESCRIPTION
**Pull request by ritzz26**
closes #42 
Video below:
https://github.com/awest25/Tennis-Video-Viewer/assets/98070074/ab2a5312-949e-4914-943e-1ebe3bae7695

Added point-click functionality to pointlist.js in order to receive position data and have the scoreboard matching the video score. The scoreboard is currently gold. Added ScoreBoard.js which handles the implementation of the actual scoreboard by using an html table with row data being collected through the video time. This works because the point click also seeks the video. Also added styling in the Home.module.css. 

Note:
Positiondata is starting on the serve for Govid's game and not on the scoreupdate for the scoreboard. The Tiebreak score for Kimmi Test is incorrectly tagged.

### CODE REVIEW

**Comment by ritzz26** [comment]
Can you suggest a range for the time? I am unable to sort that range out as of now.

**Review by awest25 — CHANGES_REQUESTED** [review]
I don’t think keeping track of when a point is selected is the right way to go here. Because we have to handle seeks anyways so it just adds unessesary code. Would something like the following work better? If I’m misunderstanding something please let me know.

```
function onPlayerStateChange(event) {
  if (event.data == YT.PlayerState.PLAYING) {
    // Start time monitoring
    startTimeMonitoring();
  } else {
    // Stop time monitoring
    stopTimeMonitoring();
  }
}

let timeMonitor;
function startTimeMonitoring() {
  function update() {
    const currentTime = videoObject.getCurrentTime() * 1000;
    updateScoreboardWithTime(currentTime);
    timeMonitor = requestAnimationFrame(update); // More efficient and synced with frame rate
  }
  update();
}

function stopTimeMonitoring() {
  cancelAnimationFrame(timeMonitor);
}
```

**Comment by awest25** [comment]
> Can you suggest a range for the time? I am unable to sort that range out as of now.

Unsure what you mean, it should just be using the last points info

**Comment by Fredenck** [comment]
noticed that clicking to a point will reverse sort the original points as well. see change below 

image
image

**Review by Fredenck — COMMENTED** [review]
1. noticed that clicking to a point will reverse sort the original points as well. see change below 
2. make sure you're commenting/deleting console.log()
3. beacuse the project is mainly in camelCase, let's stick to it for the sake of consistency

I really liked how you figured out how to incorporate the VideoPlayer's changes with useEffect every second. Also really love the bolded + arrow for current server

image
image

**Comment by awest25** [comment]
Please do not use "var" for variables because it is function-scoped. "let" and "const" make the code more readable and less prone to bugs.

**Review by awest25 — COMMENTED** [review]
see comments

**Review by awest25 — APPROVED** [review]

**Pull request merged**
